### ISSUE TITLE
Handler config not working?

### ISSUE THREAD

**Issue by PDaily** [jimmycuadra/lita#110]
So starting with Lita, I decided to write a handler as a way to get my feet wet. However, I have run into a wall in dealing with retrieving config values. 

When setting the config like so and correctly setting it in the `lita_config.rb` file:

 ```ruby
config :api_key
```
And calling it anywhere in my code:

```ruby
def thing
  config.api_key
end
```

I always end up with an error that reads:
```
undefined local variable or method `api_key' for Lita::Handlers::Destiny:Class (NameError)
```
By taking a look at my [repo], could you offer me a reason as to why this is failing?

[repo]:https://github.com/PDaily/lita-destiny

**Comment by jimmycuadra** [comment]
Did you figure this out since you created this issue? The code in the repo you linked looks correct to me, with regards to the handler configuration.

**Comment by PDaily** [comment]
Unfortunately I have not. Comparing my project with others that use config that work, everything is the same as far as I could tell. At this point I'm lost as to what needs to be done other than pushing my api_key into an ENV variable.

**Comment by jimmycuadra** [comment]
Ah, I see the issue in that code. There's two issues being confused here:

1.  `config` at the class level is for defining a configuration attribute. At the instance level, it's for accessing the configuration object at runtime.
2.  Since configuration isn't finalized until Lita starts up, you can't access values on it before that point, which is what you're attempting to do with that `person = config.name` line. What you want instead is a private instance method that will access the configuration object at runtime:

    ``` ruby
    def hello(response)
      response.reply("Hi " + person)
    end

    private

    def person
      config.name
    end
    ```

**Comment by PDaily** [comment]
Awesome. I rewrote what I have and tests pass, no other errors came around.

Thanks!
