### ISSUE TITLE
Check whether response is private?

### ISSUE THREAD

**Issue by nickjer** [jimmycuadra/lita#123]
This is more of a question to gauge your opinion before I do anything rash, like another pull request. I know right now I can do...

```
# is this a private direct message?
response.message.source.private_message?
```

to test if it is a private message sent directly to the bot. But maybe we could trickle this upstream closer to the `response` as well...

```
# is this a private direct message?
response.private_message?
```

Pros or cons?

Pro: developers who deal with separate private and public messages won't need to know about the intricacies of the `Response` object

Con: can't think of one right off the top of my head, I don't know this code well enough to judge if this is a terrible idea

**Comment by jimmycuadra** [comment]
I'd be happy to accept that in a PR. There are actually a lot of Law of Demeter violations in Lita's API because of all the interconnections between the robot, adapter, source, message, and room objects. In most cases that gap should be bridged by turning methods like `foo.bar.baz` into `foo.baz` when the meaning of the method is obvious in that context, and into `foo.bar_baz` (or something similar) when disambiguation is needed.

Perhaps also worth mentioning, though maybe not really relevant here, that `Lita::Response` may be broken apart into multiple objects in the future, since it's really more of a request object than a response object. It has elements of both, which makes it confusing (especially for new users) and not consistent with the way HTTP routes work.
