### ISSUE TITLE
Use lita as github bot

### ISSUE THREAD

**Issue by dg-ratiodata** [jimmycuadra/lita#144]
Hi @jimmycuadra,

are you aware of someone using lita as github bot, which can comment on new PRs if some information is missing? I think about automating handling of PRs/issues a bit to reduce amout of work.

Example: Today I came across GordonTheTurtle at Docker. I thought about something like the docker guys do with their @GordonTheTurtle user, example for [comment](https://github.com/docker/docker/issues/16448#issuecomment-141950489)? http://fossies.org/linux/docker/project/TOOLS.md

* It comments on PRs, if bug information is msising
* It comments on PRs, if some signature is missing
* etc.

Components I can think of.
* Information store to track status of seen PRs, after 7 days unmodified PRs are closed
* Component to get informed via [Webhook](https://github.com/jimmycuadra/lita-github-web-hooks)
* Component to comment on PRs, not found yet

Thanks a lot.

/cheers Dennis

**Comment by jimmycuadra** [comment]
Hi Dennis,

There are a few open source plugins that interact with GitHub in some way. Search for "github" on https://www.lita.io/plugins and you'll find some of them. Others can be found by searching GitHub itself (since not everyone publishes their plugins to RubyGems.) Since you have specific behavior in mind, it's unlikely that any of them will do exactly what you want, so you may be best served by building one of your own. Feel free to join us in IRC (#lita.io on the Freenode network) if you want to chat with other developers about how you might implement your ideas.

**Comment by dg-ratiodata** [comment]
> Since you have specific behavior in mind, it's unlikely that any of them will do exactly what you want

Thanks a lot for your reply. I think you're right. That was the reason I asked for some advice :-). Is there any gitter room, or does most of you guys use just irc.

**Comment by jimmycuadra** [comment]
There isn't a Gitter room I'm aware of. The IRC channel is the official place for support. There's also the [mailing list](https://groups.google.com/group/litaio) if you prefer that.
