### ISSUE TITLE
Authorization Handler crashing with special characters in name

### ISSUE THREAD

**Issue by consultantRR** [jimmycuadra/lita#73]
We have a slack user with a mention_name `jose` and a real name `Jose Pantíno` (accent over the i)

The following crashes the Authorization Handler:

`@lita auth add jose testgroup`

...with the following:

```
[2014-12-20 06:24:09 UTC] ERROR: Lita::Handlers::Authorization crashed. The exception was:
"\xC3" on US-ASCII
```

It seems the handler cannot deal with special characters. (I am assuming this is a lita issue and not a lita-slack issue.)

**Comment by jimmycuadra** [comment]
This might be the result of `Encoding.default_external` not being set to `Encoding::UTF_8`. Take a look at these links for more details, and let us know if that turns out to be the problem!

* [invalid byte sequence in US-ASCII](https://github.com/jimmycuadra/lita-hipchat/issues/3)
* [Why doesn't Encoding.default_external respect LANG?](http://stackoverflow.com/questions/27981952/why-doesnt-encoding-default-external-respect-lang)

**Comment by jimmycuadra** [comment]
Closing this as it's been idle for a while. If more help is needed, feel free to reopen!
