### ISSUE TITLE
Replies in handler only sent to slack after handler finishes

### ISSUE THREAD

**Issue by colszowka** [jimmycuadra/lita#77]
Referring to [this](https://twitter.com/TheDeadSerious/status/560432170238750720) conversation on twitter earlier today, I have this sample handler that I want to use with lita-slack:

```ruby
require 'open3'

module Lita
  module Handlers
    class Ops < Handler
      route "demo1" do |response|
        response.reply 'Got a message'
        Open3.popen2e 'ping www.github.com -c 5' do |stdin, output, wait_thr|
          while line = output.gets
            puts line
            response.reply line
          end
        end
      end
      route "demo2" do |response|
        response.reply 'hello world'
        sleep 5
      end
    end

    Lita.register_handler(Ops)
  end
end
```

In both cases, I only get the replies on slack when the method is finished. For demo1, the shell debug puts statements print immediately, so it doesn't seem that something is blocking it.

Would be great to get this figured out for chatops stuff!

**Comment by jimmycuadra** [comment]
I haven't gotten a chance to try this out myself yet, but I have a feeling it's due to the Slack handler being backed by Eventmachine and interacting strangely with the threads spawned by Lita to handle incoming messages.

**Comment by jnalley** [comment]
I've run into this as well.  In my case, I wanted to acknowledge a user's command before collecting results for a long running task.  I ended up creating an event handler as a work around.  That way I could reply quickly to the user's request, then trigger the event for the long running task.  Not the best solution, but ok as a work-around.

The eventmachine FAQ has some mention of "[working with other threads](https://github.com/eventmachine/eventmachine/wiki/FAQ)" and suggests using 'EM::next_tick'.  I'm not even sure if this is relevant.

**Comment by jimmycuadra** [comment]
Here's a simplified example that illustrates the problem from #78:

``` ruby
route /^test$/ do |response|
  response.reply("start")
  sleep 2
  response.reply("end")
end
```

**Comment by fullybaked** [comment]
I've hit this as well, with a long running deploy being fired off from the bot.  I ended up spawning a thread for the deploy process in an event handler.  It's a bit hack-y but it works.

**Comment by jimmycuadra** [comment]
As a quick fix, you can put your long running tasks inside an `EM.defer` block:

``` ruby
route /^test$/ do |response|
  response.reply("start")
  EM.defer { long_running_task }
  response.reply("end")
end
```

You shouldn't do this in a handler you're going to publish publicly, because it assumes the presence of Eventmachine and that the code is executing in an event loop, which will only be the case when using the Slack adapter.

I need to keep thinking about how to "nest" sends on the WebSocket inside callbacks to received events so that messages will be sent immediately. I'm not sure it's actually possible, but I honestly don't totally understand Eventmachine's execution model. It might make sense to redesign the adapter to use a Celluloid-based WebSocket implementation, since that tends to make asynchronous code feel more synchronous, which tends to be easier to write. That was actually my original plan, but there doesn't seem to be a Celluloid-based WebSocket implementation for Ruby that's as mature as Faye's is.

**Comment by terenced** [comment]
Have you looked into Reel?https://github.com/celluloid/reel

**Comment by jimmycuadra** [comment]
Reel is a server, but what the Slack adapter needs is a WebSocket client. [celluloid-websocket-client](https://github.com/jeremyd/celluloid-websocket-client) might work but it seems to be unmaintained, which makes me hesitant to rely on it.

**Comment by jimmycuadra** [comment]
This is fixed in [lita-slack v1.1.1](https://github.com/kenjij/lita-slack/releases/tag/v1.1.1). You should no longer have to call `EM.defer` in your handlers directly.

**Comment by colszowka** [comment]
@jimmycuadra Awesome! I can confirm that it works great now, thanks.

**Comment by terenced** [comment]
Awesome!!
