### ISSUE TITLE
Needs a CHANGELOG file

### ISSUE THREAD

**Issue by brodock** [jimmycuadra/lita#92]
Lita should have a CHANGELOG file, and should suggest plugin authors to do the same.

As an example, I'm following http://keepachangelog.com/ convention on my plugin: https://github.com/brodock/lita-hangout.

I'm considering send a PR to add a default templated CHANGELOG.md for lita plugin generators, if you agree with the cause.

**Comment by jimmycuadra** [comment]
I use GitHub's releases page for my project changelogs. Lita's can be found here: https://github.com/jimmycuadra/lita/releases. This is mentioned in the "history" section of the README. Perhaps it should be retitled "changelog" to make it more discoverable.

**Comment by brodock** [comment]
What about including a templated CHANGELOG.md for generated plugin gems? Do you think that it can be useful?

**Comment by jimmycuadra** [comment]
My selfish reaction is that I wouldn't want it, because I don't use them on my own projects and so it'd just be a file I'd have to delete manually every time. It is a pretty common practice, though, so it's probably a good idea. Maybe it could just be optional and the user could be prompted with a question asking if they want one or not. I've also been thinking a bit about the possibility of allowing Lita extensions to hook into the CLI for custom generators. That'd be a nice way to reintroduce LICENSE file generation for people who want to explicitly opt-in to it.

**Comment by jimmycuadra** [comment]
I'm going to close this since I don't have any immediate plans to introduce a changelog file for either Lita or generated plugins, but I will keep thinking about it. Thanks for the idea!
