### ISSUE TITLE
Make Puma optional.

### ISSUE THREAD

**Issue by MrJoy** [jimmycuadra/lita#95]
Ideally I should be able to plug in other web servers, or run no web server at all.  This would facilitate greater fluidity in deploying Lita, and in managing the semantic surface area that's exposed.

**Comment by jimmycuadra** [comment]
One issue I see with this is that users would have to install an additional gem in order to make Lita's web server work out of the box. (Of course there's WEBrick, but I don't want to encourage people to use that, especially not in production.) Right now Lita doesn't have any "soft" dependencies like this. Ruby environments are already tough to set up so I want things to be as plug-and-play as possible on Lita's part.

That all assumes that what you desire is not having to install Puma specifically. If having Puma installed but unused is okay (either because the web server is disabled or because you're using a different web server installed separately) then this would be an easier change to make.

**Comment by MrJoy** [comment]
Actually, the issue I faced made having Puma at all problematic.  I found a solution, but haven't yet calculated the full impact of it...

Basically, trying to set up a Docker container from the Alpine Linux base image (5MiB versus hundreds for Ubuntu) things got annoyingly complicated in a hurry.  I won -- and now have a Lita container that's ~80MiB instead of ~850MiB.  Maybe an easily-found Google blog post will provide sufficient solution.

/me queues up yet another blog post hell probably never get to writing.
